site_name: Dotnet Tips (Azərbaycanca)
site_url: https://muratdincc.github.io/dotnet-tips-azerbaijani
site_description: Bu kitab, C# və .NET texnologiyaları haqqında məsləhətlər və məlumatlar ehtiva edir. Azərbaycan dilində yazılmış məzmunlarla tərtibatçılara (proqramçı) kömək etməyi hədəfləyir.
docs_dir: docs
repo_name: muratdincc/dotnet-tips-azerbaijan
repo_url: https://github.com/muratdincc/dotnet-tips-azerbaijan
edit_uri: edit/master/docs/

theme:
  name: material
  language: az
  font:
    text: Sora
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  prev_next_buttons_location: both
  navigation_depth: 4
  titles_only: False
  sticky_navigation: True

markdown_extensions:
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: true
      
nav:
  - Ana Səhifə: index.md
  - C#:
      - Null Handling: csharp/null-handling.md
      - Record Types: csharp/record-types.md
      - Pattern Matching: csharp/pattern-matching.md
      - Expression-Bodied Members: csharp/expression-bodied-members.md
      - Tuples: csharp/tuples.md
      - Local Functions: csharp/local-functions.md
      - Async Streams: csharp/async-streams.md
      - Ref Returns and Ref Locals: csharp/ref-returns-locals.md
      - Extension Methods: csharp/extension-methods.md
      - Default Interface Methods: csharp/default-interface-methods.md
      - Static Local Functions: csharp/static-local-functions.md
      - Ranges and Indices: csharp/ranges-indices.md
      - Deconstruction: csharp/deconstruction.md
      - Immutable Collections: csharp/immutable-collections.md
      - Target-Typed New Expressions: csharp/target-typed-new.md
      - Safe Casting with `as`: csharp/safe-casting.md
      - String Interpolation: csharp/string-interpolation.md
  - .NET & ASP.NET:
      - Error Handling: dotnet/error-handling.md
      - Minimal APIs: dotnet/minimal-apis.md
      - Asinxron Proqramlaşdırma: dotnet/async-programming.md
      - Unit Testing ve Mocking: dotnet/unit-testing-mocking.md
      - Exception Logging: dotnet/exception-logging.md
      - Dependency Injection (DI): dotnet/dependency-injection.md
      - Configuration Management: dotnet/configuration-management.md
      - Middleware: dotnet/middleware-design.md
      - Authentication ve Authorization: dotnet/authentication-authorization.md
      - Logging ve Monitoring: dotnet/logging-monitoring.md
      - Routing ve URL İdarəsi: dotnet/routing-url-management.md
      - Static Files Optimizasiyası: dotnet/static-files-optimization.md
      - Caching Strategiyaları: dotnet/caching-strategies.md
      - Validation ve FluentValidation İstifadəsi: dotnet/fluent-validation.md
      - Globalization ve Localization: dotnet/globalization-localization.md
      - Response Compression ve Content Optimization: dotnet/response-compression.md
      - Health Checks ve Monitoring: dotnet/health-checks-monitoring.md
      - Background Services ve Hosted Services: dotnet/background-services.md
      - Dynamic Configuration ve Feature Flags: dotnet/dynamic-configuration.md
  - Entity Framework:
      - Tag With: entity-framework/tag-with.md
      - Splited Query: entity-framework/splited-query.md
      - Raw SQL Queries: entity-framework/raw-sql-queries.md
      - Shadow Properties: entity-framework/shadow-properties.md
      - Bulk Operations: entity-framework/bulk-operations.md
      - Value Conversions: entity-framework/value-conversions.md
      - Temporal Tables: entity-framework/temporal-tables.md
      - Keyless Entities: entity-framework/keyless-entities.md
  - Dapper:
      - Basic CRUD Funksiyaları: dapper/basic-crud-operations.md
      - Query Parameters: dapper/query-parameters.md
      - Stored Procedure: dapper/stored-procedures.md
      - Multiple Mapping: dapper/multiple-mapping.md
      - Transaction İdarəsi: dapper/transaction-management.md
      - QueryMultiple: dapper/query-multiple.md
      - Async/Await ilə Asinxron Sorğular: dapper/async-queries.md
      - N+1 Problemi: dapper/n-plus-1-problem.md
      - Bulk Funksiyaları və Performans: dapper/bulk-operations.md
  - LINQ:
      - Select, Where ve Aggregate: linq/select-where-aggregate.md
      - Performans Optimizasiyası: linq/performance.md
      - Extension Methods: linq/extension-methods.md
      - Async LINQ: linq/async-linq.md
      - AsNoTracking İdarəsi: linq/asnotracking-performance.md
      - Expression Tree ilə Dinamiq LINQ Sorğuları: linq/expression-trees.md
      - Take ve Skip ilə Səhifələmək: linq/pagination-take-skip.md
      - OrderBy ilə Performanslı Sıralama: linq/performance-orderby.md
      - Any ve All İstifadəsi: linq/any-all-usage.md
      - Select vs SelectMany Fərqləri: linq/select-vs-selectmany.md
      - First, FirstOrDefault, Single ve SingleOrDefault Fərqləri: linq/first-single-differences.md
      - Queryable ve Enumerable Arasındakı Fərqlər: linq/queryable-enumerable-differences.md
      - Lazy Evaluation ve Performansa Təsiri: linq/lazy-evaluation-performance.md
  - Garbage Collector:
      - İşləmə Mexanizması: garbage-collector/working-mechanism.md
      - Yeni Özəlliklər (.NET 9): garbage-collector/new-features-v9.md
      - Yaddaş Sızıntısının Təyini: garbage-collector/memory-leak-detection.md
  - Resiliency ve Xəta İdarəsi:
      - Polly ile Retry ve Circuit Breaker: resiliency/polly-retry-circuit-breaker.md
      - Circuit Breaker State Management: resiliency/circuit-breaker-state-management.md
      - Timeout İdarəsi: resiliency/timeout-management.md
      - Bulkhead Isolation: resiliency/bulkhead-isolation.md
      - Fallback Strategiyaları: resiliency/fallback-strategies.md
      - Transient Fault Handling: resiliency/transient-fault-handling.md
      - Chaos Engineering: resiliency/chaos-engineering.md
      - Graceful Degradation: resiliency/graceful-degradation.md
      - API Gateway ilə Resiliency: resiliency/api-gateway-resiliency.md
      - Idempotency Key və Məlumat Tutarlılığı: resiliency/idempotency-key-data-consistency.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/muratdincc
    - icon: fontawesome/brands/github
      link: https://github.com/muratdincc
    - icon: fontawesome/brands/microsoft
      link: https://mvp.microsoft.com/en-US/MVP/profile/11591845-876c-42b5-b701-5b8b21371c7f
    - icon: fontawesome/solid/rss
      link: https://muratdinc.dev

copyright: 2025 <a href="https://github.com/muratdincc">Murat Dinc</a>.